### ISSUE TITLE
Support arbitrary stream types

### ISSUE THREAD

**Issue by ieeemma** [RyanBrewer317/party#1]
Other parser combinator libraries like Haskell's Megaparsec support parsing over non-string types. This is really useful when you need a custom (eg contextual) lexer stage.

Could party support this too? It seems like it should be possible to swap all instances of `List(String)` with `List(a)`, assuming the user provides a function `a -> SourcePos` for errors. It would be very useful for a compiler I want to write in Gleam.

**Comment by RyanBrewer317** [comment]
I'm generally encouraging of your idea, but can you say more about it? It seems to me that replacing List(String) with List(a) isn't enough, since many of the combinators expect the first element of the source list to be a string character, and you'd get type errors if it's not. Would you simply not be able to use things like `char`, `string`, `digit` etc.? I can imagine that. 

The biggest issue I see is that we need backwards compatibility, now that we're past version 1.0.0. That means the types of the existing API surface can't change, so we couldn't add a type parameter to the Parser type for its source type. Therefore it seems like we'd need a second Parser type and copies of all the source-type-agnostic combinators (like `satisfy` if you can figure out the SourcePos thing, and `either` and `perhaps` etc.) would have to be written for this new type.

If we can work out a good way to do this and you want to take it on, I encourage you to make a PR! I should work on a CONTRIBUTING.md file and CODE_OF_CONDUCT.md file at some point. But hopefully you can find that the existing `party` codebase is small and approachable.

**Comment by ieeemma** [comment]
Many combinators are just specialised to string parsers - `char` and `digit` for example only work on a parser over `char`s (well, `String`s in Gleam). These are both just wrappers over `satisfy`.

The `string` combinator doesn't need to be specialised to strings, it just takes in a `List(a)` and matches them exactly, rather than taking in a `String`.

I'm not sure how to integrate this without changing the API - it would suck to duplicate all of the functionality just for a more generalized type. Would it be possible to instead make `Parser` an alias for `GenericParser` that specializes it to strings? That way the API appears unchanged, but you can use the more generalized parser type too.

I'm happy to try contributing, but I'm not as familiar with Gleam yet - I've come from a Haskell background. I'm also very busy with university finals so I may not have time to work on this for a while.

**Comment by RyanBrewer317** [comment]
A generalized type with a synonym sounds like a good idea. If I have time I might start work on this. 

I also came to Gleam from a Haskell background and found it pretty easy, personally. I'd recommend a toy project like the following lambda calculus evaluator, as a learning project: https://github.com/RyanBrewer317/ryanbrewer-dev/blob/main/src%2Ftinylang.gleam

**Comment by RyanBrewer317** [comment]
@ieeemma Play with this and tell me how it goes. If all goes well I'll merge this for the next minor version! It's possible that there are bugs here. https://github.com/RyanBrewer317/party/tree/RyanBrewer317/generalized-token-type

Note that this is not "arbitrary stream types," and I don't plan on adding those until maybe a 2.0 release, but probably never. Arbitrary stream types would allow iterators and infinite streams. Instead, this is just arbitrary *token* types.

**Comment by RyanBrewer317** [comment]
@ieeemma 
I'm thinking of holding off on this for a while, unfortunately. Type aliases in Gleam don't play well with documentation, which is a pretty big deal for a project like this whose main selling point is approachability. I've talked to the Gleam creator, Louis, and he says the documentation thing is intentional and won't change. I'll add this to the list for 2.0; in the meantime, the code in the branch I linked above gives an implementation of what you want that you can use, and I don't think I'll be adding much significant features until the 2.0 anyway.
![image](https://github.com/RyanBrewer317/party/assets/26353605/54f7b485-2e5c-4ef1-bac4-7cd58e2434fa)
